In [34]:
import pandas as pd

file_path = "../Data/cleaned_real_estate_listings.csv"

df = pd.read_csv(
    file_path,
    encoding="utf-8-sig"
)

print("Rows, Columns:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

df.head()

Rows, Columns:
(45890, 22)

Columns:
['listing_id', 'title', 'listing_type', 'category', 'city', 'district', 'price', 'area', 'price_per_sqm', 'beds', 'livings', 'bathrooms', 'street_width', 'age', 'latitude', 'longitude', 'advertiser_type', 'create_time', 'create_date', 'year', 'month', 'year_month']

,listing_id,title,listing_type,category,city,district,price,area,price_per_sqm,beds,...,street_width,age,latitude,longitude,advertiser_type,create_time,create_date,year,month,year_month
0,4331,"أرض للبيع في شارع الياقوت, الدار البيضاء, الرياض",Sale,2,الرياض,حي الدار البيضاء,1958400,816.00,"2,400.00",0.00,...,60.00,0.00,24.55,46.78,Unknown,1415294130,2014-11-06 17:15:30,2014,11,2014-11
1,4837,أرض للبيع في طريق الملك عبدالله بن عبدالعزيز ا...,Sale,2,الرياض,حي المغرزات,15078000,"1,077.00","14,000.00",0.00,...,80.00,0.00,24.75,46.72,Unknown,1416054461,2014-11-15 12:27:41,2014,11,2014-11
2,5498,أرض للبيع في 5 المملكة العربية السعودية,Sale,2,محايل,حي الروضة,8057700,"23,022.00",350.00,0.00,...,15.00,0.00,18.27,41.52,Unknown,1417220044,2014-11-29 00:14:04,2014,11,2014-11
3,6520,"أرض للإيجار في شارع الهزاعية, حي العشيرية, جدة",Rent,15,جدة,حي الرياض,50000,400.00,125.00,0.00,...,35.00,0.00,21.89,39.13,Unknown,1418232587,2014-12-10 17:29:47,2014,12,2014-12
4,8847,أرض للبيع في طريق الملك خالد ، حي الثقبة ، الخ...,Sale,2,الخبر,حي الثقبة,3000000,870.00,"3,448.28",0.00,...,15.00,0.00,26.29,50.18,Unknown,1420232812,2015-01-02 21:06:52,2015,1,2015-01

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45890 entries, 0 to 45889
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   listing_id       45890 non-null  int64
 1   title            45890 non-null  object
 2   listing_type     45890 non-null  object
 3   category         45890 non-null  int64
 4   city             45890 non-null  object
 5   district         45890 non-null  object
 6   price            45890 non-null  int64
 7   area             45890 non-null  float64
 8   price_per_sqm    45890 non-null  float64
 9   beds             45890 non-null  float64
 10  livings          45890 non-null  float64
 11  bathrooms        45890 non-null  float64
 12  street_width     44564 non-null  float64
 13  age              24207 non-null  float64
 14  latitude         45890 non-null  float64
 15  longitude        45890 non-null  float64
 16  advertiser_type  45890 non-null  object
 17  create_time      45890 non-null  int64
 18  create_date      45890 non-null  object
 19  year             45890 non-null  int64
 20  month            45890 non-null  int64
 21  year_month       45890 non-null  object
dtypes: float64(9), int64(6), object(7)
memory usage: 7.7+ MB

In [36]:
missing_values = df.isnull().sum().sort_values(ascending=False)
missing_values

age                21683
street_width        1326
listing_type           0
category               0
listing_id             0
title                  0
district               0
city                   0
price                  0
area                   0
beds                   0
price_per_sqm          0
bathrooms              0
livings                0
latitude               0
longitude              0
advertiser_type        0
create_time            0
create_date            0
year                   0
month                  0
year_month             0
dtype: int64

In [37]:
df[
    [
        "price",
        "area",
        "beds",
        "livings",
        "bathrooms",
        "street_width",
        "age"
    ]
].describe()

,price,area,beds,livings,bathrooms,street_width,age
count,"45,890.00","45,890.00","45,890.00","45,890.00","45,890.00","44,564.00","24,207.00"
mean,"3,100,627.72","1,259.67",2.17,0.88,1.89,23.74,4.92
std,"7,062,390.16","4,309.75",2.53,1.21,2.17,14.60,9.04
min,"2,700.00",21.00,0.00,0.00,0.00,0.00,0.00
25%,"625,612.50",288.00,0.00,0.00,0.00,15.00,0.00
50%,"1,200,000.00",450.00,0.00,0.00,0.00,20.00,0.00
75%,"2,600,000.00",850.00,5.00,2.00,4.00,28.00,6.00
max,"99,970,000.00","99,500.00",7.00,6.00,5.00,100.00,36.00

In [38]:
df_clean = df.copy()

df_clean.head()

,listing_id,title,listing_type,category,city,district,price,area,price_per_sqm,beds,...,street_width,age,latitude,longitude,advertiser_type,create_time,create_date,year,month,year_month
0,4331,"أرض للبيع في شارع الياقوت, الدار البيضاء, الرياض",Sale,2,الرياض,حي الدار البيضاء,1958400,816.00,"2,400.00",0.00,...,60.00,0.00,24.55,46.78,Unknown,1415294130,2014-11-06 17:15:30,2014,11,2014-11
1,4837,أرض للبيع في طريق الملك عبدالله بن عبدالعزيز ا...,Sale,2,الرياض,حي المغرزات,15078000,"1,077.00","14,000.00",0.00,...,80.00,0.00,24.75,46.72,Unknown,1416054461,2014-11-15 12:27:41,2014,11,2014-11
2,5498,أرض للبيع في 5 المملكة العربية السعودية,Sale,2,محايل,حي الروضة,8057700,"23,022.00",350.00,0.00,...,15.00,0.00,18.27,41.52,Unknown,1417220044,2014-11-29 00:14:04,2014,11,2014-11
3,6520,"أرض للإيجار في شارع الهزاعية, حي العشيرية, جدة",Rent,15,جدة,حي الرياض,50000,400.00,125.00,0.00,...,35.00,0.00,21.89,39.13,Unknown,1418232587,2014-12-10 17:29:47,2014,12,2014-12
4,8847,أرض للبيع في طريق الملك خالد ، حي الثقبة ، الخ...,Sale,2,الخبر,حي الثقبة,3000000,870.00,"3,448.28",0.00,...,15.00,0.00,26.29,50.18,Unknown,1420232812,2015-01-02 21:06:52,2015,1,2015-01

In [39]:
print(df_clean.shape)
df_clean.info()

(45890, 22)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45890 entries, 0 to 45889
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   listing_id       45890 non-null  int64
 1   title            45890 non-null  object
 2   listing_type     45890 non-null  object
 3   category         45890 non-null  int64
 4   city             45890 non-null  object
 5   district         45890 non-null  object
 6   price            45890 non-null  int64
 7   area             45890 non-null  float64
 8   price_per_sqm    45890 non-null  float64
 9   beds             45890 non-null  float64
 10  livings          45890 non-null  float64
 11  bathrooms        45890 non-null  float64
 12  street_width     44564 non-null  float64
 13  age              24207 non-null  float64
 14  latitude         45890 non-null  float64
 15  longitude        45890 non-null  float64
 16  advertiser_type  45890 non-null  object
 17  create_time      45890 non-null  int64
 18  create_date      45890 non-null  object
 19  year             45890 non-null  int64
 20  month            45890 non-null  int64
 21  year_month       45890 non-null  object
dtypes: float64(9), int64(6), object(7)
memory usage: 7.7+ MB

In [40]:
df_clean[["price", "area"]].describe()

              price      area
count     45,890.00 45,890.00
mean   3,100,627.72  1,259.67
std    7,062,390.16  4,309.75
min        2,700.00     21.00
25%      625,612.50    288.00
50%    1,200,000.00    450.00
75%    2,600,000.00    850.00
max   99,970,000.00 99,500.00

In [41]:
df_clean = df_clean[
    (df_clean["price"] > 1000) &
    (df_clean["price"] < 100000000) &
    (df_clean["area"] > 20) &
    (df_clean["area"] < 100000)
].copy()

print(df_clean.shape)

df_clean[["price", "area"]].describe()

(45890, 22)

              price      area
count     45,890.00 45,890.00
mean   3,100,627.72  1,259.67
std    7,062,390.16  4,309.75
min        2,700.00     21.00
25%      625,612.50    288.00
50%    1,200,000.00    450.00
75%    2,600,000.00    850.00
max   99,970,000.00 99,500.00

In [42]:
df_clean["price_per_sqm"] = df_clean["price"] / df_clean["area"]

df_clean[["price", "area", "price_per_sqm"]].describe()

              price      area  price_per_sqm
count     45,890.00 45,890.00      45,890.00
mean   3,100,627.72  1,259.67       3,537.64
std    7,062,390.16  4,309.75       3,239.04
min        2,700.00     21.00         100.00
25%      625,612.50    288.00       1,311.97
50%    1,200,000.00    450.00       3,000.00
75%    2,600,000.00    850.00       4,600.00
max   99,970,000.00 99,500.00      50,000.00

In [43]:
pd.set_option("display.float_format", "{:,.2f}".format)

In [44]:
df_clean = df_clean[
    (df_clean["price_per_sqm"] >= 100) &
    (df_clean["price_per_sqm"] <= 50000)
].copy()

print(df_clean.shape)

df_clean[["price", "area", "price_per_sqm"]].describe()

(45890, 22)

              price      area  price_per_sqm
count     45,890.00 45,890.00      45,890.00
mean   3,100,627.72  1,259.67       3,537.64
std    7,062,390.16  4,309.75       3,239.04
min        2,700.00     21.00         100.00
25%      625,612.50    288.00       1,311.97
50%    1,200,000.00    450.00       3,000.00
75%    2,600,000.00    850.00       4,600.00
max   99,970,000.00 99,500.00      50,000.00

In [45]:
def classify_listing_type(title):
    title = str(title)
    
    if "للبيع" in title:
        return "Sale"
    elif "للإيجار" in title or "للايجار" in title or "ايجار" in title:
        return "Rent"
    else:
        return "Unknown"

df_clean["listing_type"] = df_clean["title"].apply(classify_listing_type)

df_clean["listing_type"].value_counts()

listing_type
Sale    42467
Rent     3423
Name: count, dtype: int64

In [46]:
df_clean = df_clean[df_clean["listing_type"] != "Unknown"].copy()

df_clean["listing_type"].value_counts()

listing_type
Sale    42467
Rent     3423
Name: count, dtype: int64

In [47]:
df_clean["create_time"].head()

0    1415294130
1    1416054461
2    1417220044
3    1418232587
4    1420232812
Name: create_time, dtype: int64

In [48]:
df_clean["create_date"] = pd.to_datetime(df_clean["create_time"], unit="s")

df_clean[["create_time", "create_date"]].head()

   create_time         create_date
0   1415294130 2014-11-06 17:15:30
1   1416054461 2014-11-15 12:27:41
2   1417220044 2014-11-29 00:14:04
3   1418232587 2014-12-10 17:29:47
4   1420232812 2015-01-02 21:06:52

In [49]:
df_clean["year"] = df_clean["create_date"].dt.year
df_clean["month"] = df_clean["create_date"].dt.month
df_clean["year_month"] = df_clean["create_date"].dt.to_period("M").astype(str)

df_clean[["create_date", "year", "month", "year_month"]].head()

          create_date  year  month year_month
0 2014-11-06 17:15:30  2014     11    2014-11
1 2014-11-15 12:27:41  2014     11    2014-11
2 2014-11-29 00:14:04  2014     11    2014-11
3 2014-12-10 17:29:47  2014     12    2014-12
4 2015-01-02 21:06:52  2015      1    2015-01

In [50]:
df_clean["create_date"].min(), df_clean["create_date"].max()

(Timestamp('2014-11-06 17:15:30'), Timestamp('2022-05-16 09:17:51'))

In [51]:
df_clean.isnull().sum().sort_values(ascending=False)

age                21683
street_width        1326
listing_type           0
category               0
listing_id             0
title                  0
district               0
city                   0
price                  0
area                   0
beds                   0
price_per_sqm          0
bathrooms              0
livings                0
latitude               0
longitude              0
advertiser_type        0
create_time            0
create_date            0
year                   0
month                  0
year_month             0
dtype: int64

In [52]:
# Drop columns with too many missing values or low analytical value
columns_to_drop = ["rent_period", "type", "length", "width"]

df_clean = df_clean.drop(columns=columns_to_drop)

# Fill missing values for property room-related columns
df_clean["beds"] = df_clean["beds"].fillna(0)
df_clean["wc"] = df_clean["wc"].fillna(0)
df_clean["livings"] = df_clean["livings"].fillna(0)

# Fill missing advertiser type as Unknown
df_clean["advertiser_type"] = df_clean["advertiser_type"].fillna("Unknown")

KeyError: "['rent_period', 'type', 'length', 'width'] not found in axis"

In [ ]:
df_clean.isnull().sum().sort_values(ascending=False)

In [ ]:
df_clean.duplicated().sum()

In [ ]:
df_clean["id"].duplicated().sum()

In [ ]:
df_clean = df_clean.rename(columns={
    "id": "listing_id",
    "location.lat": "latitude",
    "location.lng": "longitude",
    "wc": "bathrooms"
})

df_clean.columns.tolist()

In [ ]:
final_columns = [
    "listing_id",
    "title",
    "listing_type",
    "category",
    "city",
    "district",
    "price",
    "area",
    "price_per_sqm",
    "beds",
    "livings",
    "bathrooms",
    "street_width",
    "age",
    "latitude",
    "longitude",
    "advertiser_type",
    "create_time",
    "create_date",
    "year",
    "month",
    "year_month"
]

df_clean = df_clean[final_columns]

df_clean.head()

In [ ]:
print(df_clean.shape)
df_clean.info()

In [ ]:
df_clean = df_clean.rename(columns={
    "year": "listing_year",
    "month": "listing_month",
    "year_month": "period_month"
})

print("Columns renamed successfully")
print(df_clean.columns.tolist())

In [ ]:
output_path = "../Data/cleaned_real_estate_listings.csv"

df_clean.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("Cleaned file saved successfully")

In [ ]:
output_path = "../Data/cleaned_real_estate_listings_mysql.csv"

df_clean.to_csv(
    output_path,
    index=False,
    encoding="utf-8"
)

print("MySQL CSV saved successfully")
print(df_clean.shape)